### ISSUE TITLE
Four 'unknown' pitches for each player?

### ISSUE THREAD

**Issue by albertlyu** [kruser/pitchfx-site#48] opened 2014-03-08 00:31 UTC
I first noticed this before I installed Modernizr made this comment https://github.com/kruser/pitchfx-site/issues/34#issuecomment-37078495

From the site:
![image](https://f.cloud.github.com/assets/1390356/2363829/f01c7870-a656-11e3-8fe3-9ebaccbb3dd4.png)

Before installing Modernizr:
![image](https://f.cloud.github.com/assets/1390356/2363871/38b2a31a-a658-11e3-8531-068b5474d899.png)

To replicate potential issue, I uninstalled Modernizr with 'bower uninstall modernizr' while in pitchfx-site/app.

Actually it looks like a coincidence that Kershaw's has four 'other' balls, and showing four 'unknown' strikes without Modernizr. But wanted to open this issue in case there are unintended extra pitches. May not need too much time to spend looking into, just found it curious -- I haven't proved that there is a potential bug here, but if I find more evidence, I'll comment here.

**Comment by kruser** [comment] 2014-03-08 18:31
There is no bug here. Missing the modernizr library is going to cause all sorts of uncaught exceptions.

There is a bug though, with the date controls not initializing now, so I'll publish a fix for that tonight. When I originally tested it, it worked just fine, but I suspect that's because I was pulling the filters from localStorage, where I cache your filter for a couple hours. Once that dies out, the filter isn't initializing nicely.

**Comment by kruser** [comment] 2014-03-10 03:57
Closing this one out since there is not a bug directly related to it. 

Still trying to tackle #49.

**Closed as completed by kruser** 2014-03-10 03:57 UTC
